/*
 * OWL - OCaml Scientific and Engineering Computing
 * Copyright (c) 2016-2018 Liang Wang <liang.wang@cl.cam.ac.uk>
 */

#define OWL_OMP_THRESHOLD_RECI 0

#define OWL_OMP_THRESHOLD_ABS 100000

#define OWL_OMP_THRESHOLD_ABS2 28358

#define OWL_OMP_THRESHOLD_SIGNUM 100000

#define OWL_OMP_THRESHOLD_SQR 18227

#define OWL_OMP_THRESHOLD_SQRT 100000

#define OWL_OMP_THRESHOLD_CBRT 884

#define OWL_OMP_THRESHOLD_EXP 1698

#define OWL_OMP_THRESHOLD_EXPM1 0

#define OWL_OMP_THRESHOLD_LOG 0

#define OWL_OMP_THRESHOLD_LOG1P 0

#define OWL_OMP_THRESHOLD_SIN 159

#define OWL_OMP_THRESHOLD_COS 81

#define OWL_OMP_THRESHOLD_TAN 0

#define OWL_OMP_THRESHOLD_ASIN 0

#define OWL_OMP_THRESHOLD_ACOS 123

#define OWL_OMP_THRESHOLD_ATAN 0

#define OWL_OMP_THRESHOLD_SINH 0

#define OWL_OMP_THRESHOLD_COSH 0

#define OWL_OMP_THRESHOLD_TANH 166

#define OWL_OMP_THRESHOLD_ASINH 0

#define OWL_OMP_THRESHOLD_ACOSH 0

#define OWL_OMP_THRESHOLD_ATANH 466

#define OWL_OMP_THRESHOLD_ERF 47

#define OWL_OMP_THRESHOLD_ERFC 660

#define OWL_OMP_THRESHOLD_LOGISTIC 1980

#define OWL_OMP_THRESHOLD_RELU 85193

#define OWL_OMP_THRESHOLD_SOFTPLUS 0

#define OWL_OMP_THRESHOLD_SOFTSIGN 100000

#define OWL_OMP_THRESHOLD_SIGMOID 22711

#define OWL_OMP_THRESHOLD_CUMMAX 20000

#define OWL_OMP_THRESHOLD_DIFF 1000

#define OWL_OMP_THRESHOLD_CUMSUM 1000

#define OWL_OMP_THRESHOLD_CUMPROD 1000
