/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Fri Feb 23 20:31:13 1996
 */
#ifdef ANSIC
/*
extern float acosf ( float x );
extern float acoshf ( float xx );
*/
extern int airyf ( float xx, float *ai, float *aip, float *bi, float *bip );
/*
extern float asinf ( float xx );
extern float asinhf ( float xx );
extern float atan2f ( float y, float x );
extern float atanf ( float xx );
extern float atanhf ( float xx );
extern float bdtrcf ( int k, int n, float pp );
extern float bdtrf ( int k, int n, float pp );
extern float bdtrif ( int k, int n, float yy );
extern float betaf ( float aa, float bb );
extern float cabsf ( cmplxf *z );
extern void cacosf ( cmplxf *z, cmplxf *w );
extern void caddf ( cmplxf *a, cmplxf *b, cmplxf *c );
extern void casinf ( cmplxf *z, cmplxf *w );
extern void catanf ( cmplxf *z, cmplxf *w );
extern float cbrtf ( float xx );
extern void cchshf ( float xx, float *c, float *s );
extern void ccosf ( cmplxf *z, cmplxf *w );
extern void ccotf ( cmplxf *z, cmplxf *w );
extern void cdivf ( cmplxf *a, cmplxf *b, cmplxf *c );
extern float ceilf ( float x );
extern void cexpf ( cmplxf *z, cmplxf *w );
*/
extern float chbevlf ( float x, float *array, int n );
/*
extern float chdtrcf ( float dff, float xx );
extern float chdtrf ( float dff, float xx );
extern float chdtrif ( float dff, float yy );
extern void clogf ( cmplxf *z, cmplxf *w );
extern void cmovf ( short *a, short *b );
extern void cmulf ( cmplxf *a, cmplxf *b, cmplxf *c );
extern void cnegf ( cmplxf *a );
extern float cosdgf ( float xx );
extern float cosf ( float xx );
extern float coshf ( float xx );
extern float cotdgf ( float x );
extern float cotf ( float x );
extern void csinf ( cmplxf *z, cmplxf *w );
extern void csqrtf ( cmplxf *z, cmplxf *w );
extern void csubf ( cmplxf *a, cmplxf *b, cmplxf *c );
extern void ctanf ( cmplxf *z, cmplxf *w );
extern float ctansf ( cmplxf *z );
*/
extern float dawsnf ( float xxx );
/*
extern int dprec ( void );
extern float ellief ( float phia, float ma );
extern float ellikf ( float phia, float ma );
extern float ellpef ( float xx );
extern int ellpjf ( float uu, float mm, float *sn, float *cn, float *dn, float *ph );
extern float ellpkf ( float xx );
extern float erfcf ( float aa );
extern float erff ( float xx );
extern float exp10f ( float xx );
extern float exp2f ( float xx );
*/
extern float expf ( float xx );
/*
extern float expnf ( int n, float xx );
extern float facf ( int i );
extern float fdtrcf ( int ia, int ib, float xx );
extern float fdtrf ( int ia, int ib, int xx );
extern float fdtrif ( int ia, int ib, float yy );
extern float floorf ( float x );
extern void fresnlf ( float xxa, float *ssa, float *cca );
extern float frexpf ( float x, int *pw2 );
*/
extern float gammaf ( float xx );
/*
extern float gdtrcf ( float aa, float bb, float xx );
extern float gdtrf ( float aa, float bb, float xx );
extern float hyp2f0f ( float aa, float bb, float xx, int type, float *err );
extern float hyp2f1f ( float aa, float bb, float cc, float xx );
*/
extern float hypergf ( float aa, float bb, float xx );
extern float i0ef ( float x );
extern float i0f ( float x );
extern float i1ef ( float xx );
extern float i1f ( float xx );
/*
extern float igamcf ( float aa, float xx );
extern float igamf ( float aa, float xx );
extern float igamif ( float aa, float yy0 );
extern float incbetf ( float aaa, float bbb, float xxx );
extern float incbif ( float aaa, float bbb, float yyy0 );
extern float incbpsf ( float aa, float bb, float xx );
*/
extern float ivf ( float v, float x );
extern float j0f ( float xx );
extern float j1f ( float xx );
extern float jnf ( int n, float xx );
extern float jvf ( float nn, float xx );
extern float k0ef ( float xx );
extern float k0f ( float xx );
extern float k1ef ( float xx );
extern float k1f ( float xx );
extern float knf ( int nnn, float xx );
/*
extern float ldexpf ( float x, int pw2 );
extern int ldprec ( void );
*/
extern float lgamf ( float xx );
/*
extern float log10f ( float xx );
extern float log2f ( float xx );
extern float logf ( float xx );
*/
extern int mtherr ( char *name, int code );
/*
extern float nbdtrcf ( int k, int n, float pp );
extern float nbdtrf ( int k, int n, float pp );
extern float ndtrf ( float aa );
extern float ndtrif ( float yy0 );
extern float onef2f ( float aa, float bb, float cc, float xx, float *err );
extern float p1evlf ( float xx, float *coef, int N );
extern float pdtrcf ( int k, float mm );
extern float pdtrf ( int k, float mm );
extern float pdtrif ( int k, float yy );
extern void poladdf ( float a[], int na, float b[], int nb, float c[] );
extern void polclrf ( float *a, int n );
extern int poldivf ( float a[], int na, float b[], int nb, float c[] );
extern float polevaf ( float *a, int na, float xx );
*/
extern float polevlf ( float xx, float *coef, int N );
/*
extern void polinif ( int maxdeg );
extern void polmovf ( float *a, int na, float *b );
extern void polmulf ( float a[], int na, float b[], int nb, float c[] );
extern void polprtf ( float *a, int na, int d );
extern void polsbt ( float a[], int na, float b[], int nb, float c[] );
extern void polsubf ( float a[], int na, float b[], int nb, float c[] );
extern float powf ( float x, float y );
extern float powif ( float x, int nn );
extern float psif ( float xx );
extern float redupif ( float xx );
extern float rgammaf ( float xx );
extern int shichif ( float xx, float *si, float *ci );
extern int sicif ( float xx, float *si, float *ci );
extern float sindgf ( float xx );
extern float sinf ( float xx );
extern float sinhf ( float xx );
extern float spencef ( float xx );
extern int sprec ( void );
extern float sqrtf ( float xx );
extern float stdtrf ( int k, float tt );
*/
extern float struvef ( float vv, float xx );
/*
extern float tandgf ( float x );
extern float tanf ( float x );
extern float tanhf ( float xx );
extern float threef0f ( float aa, float bb, float cc, float xx, float *err );
*/
extern float y0f ( float xx );
extern float y1f ( float xx );
extern float ynf ( int nn, float xx );
/*
extern float yvf ( float vv, float xx );
extern float zetacf ( float xx );
extern float zetaf ( float xx, float qq );
*/
#endif
