name: Multiple MacOSes

on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14 # beta runner for macos arm64
          - macos-latest
          # - ubuntu-latest
        ocaml-compiler:
          - "5.2"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          opam-local-packages: |
            *.opam

      - name: Deps
        run: |
          brew install llvm libomp
          export CC=/usr/local/opt/llvm/bin/clang
          export CXX=/usr/local/opt/llvm/bin/clang++

      - run: opam depext owl --with-test
    
      - run: |
          opam install owl-base --yes --deps-only --with-test
          opam exec -- dune build -p owl-base
          opam exec -- dune runtest -p owl-base
  
      - run: |
          opam install owl --yes --deps-only --with-test
          opam exec -- dune build -p owl
          opam exec -- dune runtest -p owl
  
      - run: |
          opam install owl-top --yes --deps-only --with-test
          opam exec -- dune build -p owl-top
          opam exec -- dune runtest -p owl-top
